# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.CharField(default='other', max_length=500),
        ),
    ]
